### ISSUE TITLE
Change the default copyright

### ISSUE THREAD

**Issue by IndiAsh** [lifted-studios/AutoCopyright#13]
Is there any way that someone can change the default copyright?
I opened the settings file and is not there.

**Comment by lee-dohm** [comment]
After you install the plugin, the first time you execute the Insert Copyright command, it should open the settings file for you.  If this is not the case, you can do this:
1. Start Sublime Text
2. Click Alt+Shift+P (or Command+Shift+P on a Mac) and select `Preferences: Browse Packages` from the command list.  This will open the Packages directory for you.
3. Open the User folder.
4. Open the `AutoCopyright.sublime-settings` file.

Both the owner text(s) and copyright message can be edited there.  `%y` is the replacement text for the copyright year or year range and `%o` is the replacement text for the copyright owner.

**Comment by IndiAsh** [comment]
Thank you
I didnt realize that the file was in user folder.

**Comment by lee-dohm** [comment]
You're welcome, I'm glad I could help and thanks for using AutoCopyright!
