### ISSUE TITLE
"Insert/Update Copyright" commands not showing up

### ISSUE THREAD

**Issue by An-dz** [lifted-studios/AutoCopyright#23]
I installed AutoCopyright with Package Control and manually but the commands to insert or update don't show up. This error shows up 4 times in the console when loading:

> Traceback (most recent call last):
>  File ".\sublime_plugin.py", line 62, in reload_plugin
>  File ".\CopyrightCommand.py", line 5, in <module>
>    import AutoCopyright.constants
> ImportError: No module named AutoCopyright.constants

I tried disabling other plugins I installed but the error persists.

**Comment by lee-dohm** [comment]
You're using AutoCopyright with Sublime Text 2?

**Comment by An-dz** [comment]
Yes

**Comment by lee-dohm** [comment]
The version at the tip does not work for ST2 and I'm waiting on the owner of Package Control to add my change to the repositories channel that will fix the issue.  The workaround, if you're familiar with git, is to do the following:
1. Go to the Packages directory on the command line.  You can find it by using: `Preferences` | `Browse Packages...`
2. Check out the repository: `git clone git://github.com/lifted-studios/AutoCopyright`
3. Change to the `v1.0.0` tag: `git checkout v1.0.0`

Alternatively, you can also download the [zip of version 1.0.0](https://nodeload.github.com/lifted-studios/AutoCopyright/zip/v1.0.0) and extract it to the `AutoCopyright` folder in the Packages directory.

Let me know if that helps ...

**Comment by An-dz** [comment]
Yes, it's working now. Thanks a lot!

**Comment by lee-dohm** [comment]
I'm glad to hear it!  Sorry about the mixup :beers:

**Comment by An-dz** [comment]
No problem, at least this handy plugin is now working. :beers: I'll drop some ideas and probably make a Pull Request in the future because I already included a feature in the code for my need and maybe you'll have interest to push. But I need to polish it and make some testings first.

**Comment by Kozlov-V** [comment]
this not whork

**Comment by lee-dohm** [comment]
@Kozlov-V The standard instructions should work now. This was just a temporary work-around while I was working with the Package Control folks to update my plugin's configuration. Try the standard instructions in the [README](https://github.com/lifted-studios/AutoCopyright/blob/master/README.md) and if it doesn't work, open a new bug with some explanation as to what is going on. I'll be happy to help.
