### ISSUE TITLE
Complete last modified date

### ISSUE THREAD

**Issue by gabrielefronze** [lifted-studios/AutoCopyright#27]
Hello,
I've a small cent to enhance this already functional package.
What about having a hotkey to press to insert the last day the file has been modified, with both DD/MM/YYYY and MM/DD/YYYY formats?

I'd like to get something like:

```
//
//  Filename.extension
//
//  Created by John Doe on 21/12/15.
//  Copyright © 2015 John Doe. All rights reserved.
//
```

With many thanks

gf

**Comment by lee-dohm** [comment]
I apologize, but we're no longer developing this package. You may be interested in the [FileHeader package](https://packagecontrol.io/packages/FileHeader) instead which does support multiple date formats.
